#
# USB peripheral controller drivers (Android legacy)
#

obj-$(CONFIG_USB_G_ANDROID_LEGACY)	+= android.o
obj-$(CONFIG_USB_ANDROID_ACM)		+= f_acm.o u_serial.o
obj-$(CONFIG_USB_ANDROID_ADB)		+= f_adb.o
obj-$(CONFIG_USB_ANDROID_MASS_STORAGE)	+= f_mass_storage.o
obj-$(CONFIG_USB_ANDROID_MTP)		+= f_mtp.o
obj-$(CONFIG_USB_ANDROID_RNDIS)		+= f_rndis.o u_ether.o
obj-$(CONFIG_USB_ANDROID_ACCESSORY)	+= f_accessory.o
